### ISSUE TITLE
Any ideas to implement dynamic library?

### ISSUE THREAD

**Issue by pavel-odintsov** [yasuhiro-ohara-ntt/bgpdump2#3]
Helo!

I'm using libbgpdump for a while but it's very slow :( bgpdump2 looks promising. Do you have any plans to support dynamic library for parsing MRT files?

**Comment by yasuhironet** [comment]
No plan so far. Do you mean dynamic link library ? Would you explain why you wanted to have it ?

**Comment by pavel-odintsov** [comment]
Yep, I mean dynamic link library. I want it because current implementations are VERY slow :(

**Comment by yasuhironet** [comment]
I guess you want your app to dynamically link the bgpdump2's dynamic link library,
so that you don't need to recompile your app but the speed is better, correct ?

In order to do so, we're going to need to adapt to the libbgpdump's API. (Else, we
will need compilation anyway.)
I think adapting/employing the original libbgpdump's API is hard,
and it may be even possible that when we implement libbgpdump's API
our implementation becomes also slow (not sure, just guessing).

I guess we have a better (different) way to solve your issue..
Can you share what is your use case ?

**Comment by pavel-odintsov** [comment]
Hello! 

I'm author and I could change my app as I want :) So libbgpdump compatibility is not required at all!

**Comment by yasuhironet** [comment]
Okay, I started to understand. :)

So we will need a good API so you can use it easily. I admit that the internal API that I'm
using is not good enough for the purpose.

Designing a good API is another challenge, and it is similar to refactoring of the code.

So the next TODO is the refactoring the code, designing a better API, and
publish it as the API for developers ....

**Comment by pavel-odintsov** [comment]
Hello!

Songsv really great! Please poke me when you finish API ;)

On Wednesday, 9 December 2015, Yasuhiro Ohara notifications@github.com
wrote:

> Okay, I started to understand. :)
> 
> So we will need a good API so you can use it easily. I admit that the
> internal API that I'm
> using is not good enough for the purpose.
> 
> Designing a good API is another challenge, and it is similar to
> refactoring of the code.
> 
> So the next TODO is the refactoring the code, designing a better API, and
> publish it as the API for developers ....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yasuhiro-ohara-ntt/bgpdump2/issues/3#issuecomment-163074075
> .

## 

Sincerely yours, Pavel Odintsov

**Comment by yasuhironet** [comment]
I am going to close this issue due to no progress for a long time.
Feel free to re-open the issue if you need it.
