### ISSUE TITLE
Short RIB file is not parsed

### ISSUE THREAD

**Issue by asergeyev** [yasuhiro-ohara-ntt/bgpdump2#6]
It looks like that when a file is shorter than bufsize, bgpdump2 would not parse it. Even if large file that's parsed correctly at first is handled with something like "-N 3221225472" it'll not print found records anymore.

**Comment by yasuhironet** [comment]
I am sorry for leaving this for a long time.

The latest commit: commit f325f9c5c477fbc5ce566407d41debafec1d21ed
might resolve this issue.

When the file is not bzip2'ed nor gzipped, and if it is the last fread read (of the buffer size),
bgpdump2 has been mistakenly dropping the buffer contents.
This bug is fixed very recently.

**Comment by asergeyev** [comment]
Feel free to close this, I appreciate you getting back to me!
